import { DraftingLine, DraftingArc, DraftingText, DraftingHatch } from '../models/drafting';
import { IDraftingEntity } from '../interfaces/entities';

export interface ParityReport {
    isValid: boolean;
    totalDxfEntities: number;
    totalDraftingEntities: number;
    discrepancies: Array<{
        index: number;
        dxfEntity: string;
        draftingEntity: string;
        diff: any;
    }>;
}

interface DxfBlock {
    type: string;
    params: Map<string, string>;
}

function parseDxf(lines: string[]): DxfBlock[] {
    const blocks: DxfBlock[] = [];
    let currentBlock: DxfBlock | null = null;
    let flat = lines.join('\n').split('\n');

    for (let i = 0; i < flat.length; i += 2) {
        let code = flat[i];
        let val = flat[i + 1];
        
        if (code === undefined || val === undefined) continue;
        
        code = code.trim();
        val = val.trim();

        if (code === '0') {
            if (currentBlock && currentBlock.type !== 'VIEW_START' && currentBlock.type !== 'VIEW_END') {
                blocks.push(currentBlock);
            }
            currentBlock = { type: val, params: new Map() };
        } else if (currentBlock) {
            currentBlock.params.set(code, val);
        }
    }
    
    if (currentBlock && currentBlock.type !== 'VIEW_START' && currentBlock.type !== 'VIEW_END') {
        blocks.push(currentBlock);
    }
    
    return blocks;
}

/**
 * Mathematically validates that the immutable DraftingEntities exactly match the 
 * raw AutoLISP DXF string arrays generated by the legacy context.
 */
export class DualOutputValidator {
    
    public static validateParity(dxfLines: string[], draftingEntities: ReadonlyArray<IDraftingEntity>): ParityReport {
        const blocks = parseDxf(dxfLines);
        let isValid = true;
        const discrepancies: any[] = [];
        const EPSILON = 0.001;
        
        if (blocks.length !== draftingEntities.length) {
            isValid = false;
            discrepancies.push({
                index: -1,
                dxfEntity: 'LENGTH_MISMATCH',
                draftingEntity: 'LENGTH_MISMATCH',
                diff: { dxfCount: blocks.length, draftingCount: draftingEntities.length }
            });
        }
        
        const minLen = Math.min(blocks.length, draftingEntities.length);
        
        for (let i = 0; i < minLen; i++) {
            const b = blocks[i];
            const e = draftingEntities[i];
            
            let match = false;
            let diff: any = null;

            if (e.draftingType === 'Line' && b.type === 'LINE') {
                const line = e as DraftingLine;
                const x1 = parseFloat(b.params.get('10') || '0');
                const y1 = parseFloat(b.params.get('20') || '0');
                const x2 = parseFloat(b.params.get('11') || '0');
                const y2 = parseFloat(b.params.get('21') || '0');
                
                if (Math.abs(line.start.x - x1) > EPSILON || Math.abs(line.start.y - y1) > EPSILON ||
                    Math.abs(line.end.x - x2) > EPSILON || Math.abs(line.end.y - y2) > EPSILON) {
                    diff = { dxf: {x1, y1, x2, y2}, drafting: {x1: line.start.x, y1: line.start.y, x2: line.end.x, y2: line.end.y} };
                } else {
                    match = true;
                }
            } else if (e.draftingType === 'Arc' && (b.type === 'ARC' || b.type === 'CIRCLE')) {
                const arc = e as DraftingArc;
                const cx = parseFloat(b.params.get('10') || '0');
                const cy = parseFloat(b.params.get('20') || '0');
                const r = parseFloat(b.params.get('40') || '0');
                if (Math.abs(arc.center.x - cx) > EPSILON || Math.abs(arc.center.y - cy) > EPSILON || Math.abs(arc.radius - r) > EPSILON) {
                    diff = { dxf: {cx, cy, r}, drafting: {cx: arc.center.x, cy: arc.center.y, r: arc.radius} };
                } else {
                    match = true;
                }
            } else if (e.draftingType === 'Text' && b.type === 'TEXT') {
                const txt = e as DraftingText;
                const val = b.params.get('1') || '';
                const x = parseFloat(b.params.get('10') || '0');
                const y = parseFloat(b.params.get('20') || '0');
                if (txt.text !== val || Math.abs(txt.position.x - x) > EPSILON || Math.abs(txt.position.y - y) > EPSILON) {
                    diff = { dxf: {text: val, x, y}, drafting: {text: txt.text, x: txt.position.x, y: txt.position.y} };
                } else {
                    match = true;
                }
            } else if (e.draftingType === 'Hatch' && b.type === 'SOLID') {
                const hatch = e as DraftingHatch;
                const x0 = parseFloat(b.params.get('10') || '0');
                const y0 = parseFloat(b.params.get('20') || '0');
                if (Math.abs(hatch.boundaryPoints[0].x - x0) > EPSILON || Math.abs(hatch.boundaryPoints[0].y - y0) > EPSILON) {
                    diff = { dxf: {x0, y0}, drafting: hatch.boundaryPoints[0] };
                } else {
                    match = true;
                }
            } else if (e.draftingType === 'Line' && b.type === 'POLYLINE') {
                // Ignore complexity of POLYLINE breaking for now, we just mark it mismatched if strict parity fails
                diff = { reason: 'Complex Polyline Unrolled', dxfType: b.type, draftingType: e.draftingType };
            } else {
                diff = { reason: 'Type Mismatch', dxfType: b.type, draftingType: e.draftingType };
            }

            if (!match) {
                isValid = false;
                discrepancies.push({
                    index: i,
                    dxfEntity: b.type,
                    draftingEntity: e.draftingType,
                    diff
                });
            }
        }

        return {
            isValid,
            totalDxfEntities: blocks.length,
            totalDraftingEntities: draftingEntities.length,
            discrepancies
        };
    }
}
