/**
 * Translation keys for the AutoCAD-parity property names the Properties
 * palette shows ("Layer", "Start X", "Lineweight"…) and for its group
 * headings ("Geometry", "Text"…).
 *
 * The names themselves live on each entity's `getPropertiesSchema()` in
 * `core/models`, which is shared with non-UI code (DXF export, the AI agent)
 * and stays in English there. The panel is the only place a drafter reads
 * them, so the English label is mapped to a key here at render time and the
 * literal is kept as the fallback: a label added to a schema later still
 * renders, untranslated, instead of vanishing.
 *
 * Values that come from the drawing — layer, block, linetype and style NAMES —
 * are deliberately absent: those are user data, not UI text.
 */
export const PROPERTY_LABEL_KEYS: Readonly<Record<string, string>> = {
  "Anchor 1": "editor.ui.props.label.anchor1",
  "Anchor 2": "editor.ui.props.label.anchor2",
  "Angle": "editor.ui.props.label.angle",
  "Annotative": "editor.ui.props.label.annotative",
  "Arc Length": "editor.ui.props.label.arcLength",
  "Area": "editor.ui.props.label.area",
  "Arrow Aspect": "editor.ui.props.label.arrowAspect",
  "Arrow Size": "editor.ui.props.label.arrowSize",
  "Arrow Type": "editor.ui.props.label.arrowType",
  "Associative": "editor.ui.props.label.associative",
  "Associativity": "editor.ui.props.label.associativity",
  "Attachment": "editor.ui.props.label.attachment",
  "Background Color": "editor.ui.props.label.backgroundColor",
  "Background Mask": "editor.ui.props.label.backgroundMask",
  "Base X": "editor.ui.props.label.baseX",
  "Base Y": "editor.ui.props.label.baseY",
  "Block Callout": "editor.ui.props.label.blockCallout",
  "Block Name": "editor.ui.props.label.blockName",
  "Bold": "editor.ui.props.label.bold",
  "Border Color": "editor.ui.props.label.borderColor",
  "Border Weight": "editor.ui.props.label.borderWeight",
  "Boundaries": "editor.ui.props.label.boundaries",
  "Brightness %": "editor.ui.props.label.brightness",
  "Cell Padding": "editor.ui.props.label.cellPadding",
  "Cells (TSV)": "editor.ui.props.label.cellsTsv",
  "Center X": "editor.ui.props.label.centerX",
  "Center Y": "editor.ui.props.label.centerY",
  "Char Spacing": "editor.ui.props.label.charSpacing",
  "Circumference": "editor.ui.props.label.circumference",
  "Closed": "editor.ui.props.label.closed",
  "Color": "editor.ui.props.label.color",
  "Cols": "editor.ui.props.label.cols",
  "Content": "editor.ui.props.label.content",
  "Contrast %": "editor.ui.props.label.contrast",
  "Decimal Separator": "editor.ui.props.label.decimalSeparator",
  "Default Align": "editor.ui.props.label.defaultAlign",
  "Default Font": "editor.ui.props.label.defaultFont",
  "Default Size": "editor.ui.props.label.defaultSize",
  "Default Text Color": "editor.ui.props.label.defaultTextColor",
  "Default VAlign": "editor.ui.props.label.defaultValign",
  "Detach Anchor 1": "editor.ui.props.label.detachAnchor1",
  "Detach Anchor 2": "editor.ui.props.label.detachAnchor2",
  "Diameter": "editor.ui.props.label.diameter",
  "Dim Style": "editor.ui.props.label.dimStyle",
  "Dogleg Length": "editor.ui.props.label.doglegLength",
  "Double Hatch": "editor.ui.props.label.doubleHatch",
  "Draw Order": "editor.ui.props.label.drawOrder",
  "End Angle": "editor.ui.props.label.endAngle",
  "End X": "editor.ui.props.label.endX",
  "End Y": "editor.ui.props.label.endY",
  "Extension Gap": "editor.ui.props.label.extensionGap",
  "Extension Past": "editor.ui.props.label.extensionPast",
  "File": "editor.ui.props.label.file",
  "Flip Text": "editor.ui.props.label.flipText",
  "Font": "editor.ui.props.label.font",
  "Global width": "editor.ui.props.label.globalWidth",
  "Hatch Style": "editor.ui.props.label.hatchStyle",
  "Height": "editor.ui.props.label.height",
  "ISO Pen Width": "editor.ui.props.label.isoPenWidth",
  "Island Detection": "editor.ui.props.label.islandDetection",
  "Italic": "editor.ui.props.label.italic",
  "Justify": "editor.ui.props.label.justify",
  "Landing Length": "editor.ui.props.label.landingLength",
  "Layer": "editor.ui.props.label.layer",
  "Length": "editor.ui.props.label.length",
  "Line Spacing": "editor.ui.props.label.lineSpacing",
  "Linetype": "editor.ui.props.label.linetype",
  "Linetype Scale": "editor.ui.props.label.linetypeScale",
  "Lineweight": "editor.ui.props.label.lineweight",
  "Oblique Angle": "editor.ui.props.label.obliqueAngle",
  "Opacity": "editor.ui.props.label.opacity",
  "Origin X": "editor.ui.props.label.originX",
  "Origin Y": "editor.ui.props.label.originY",
  "Pattern Name": "editor.ui.props.label.patternName",
  "Position X": "editor.ui.props.label.positionX",
  "Position Y": "editor.ui.props.label.positionY",
  "Precision": "editor.ui.props.label.precision",
  "Prefix": "editor.ui.props.label.prefix",
  "Radius": "editor.ui.props.label.radius",
  "Rotation": "editor.ui.props.label.rotation",
  "Round Off": "editor.ui.props.label.roundOff",
  "Rows": "editor.ui.props.label.rows",
  "Scale": "editor.ui.props.label.scale",
  "Scale X": "editor.ui.props.label.scaleX",
  "Scale Y": "editor.ui.props.label.scaleY",
  "Show Header Row": "editor.ui.props.label.showHeaderRow",
  "Show Title Row": "editor.ui.props.label.showTitleRow",
  "Solid Fill": "editor.ui.props.label.solidFill",
  "Spacing": "editor.ui.props.label.spacing",
  "Start Angle": "editor.ui.props.label.startAngle",
  "Start X": "editor.ui.props.label.startX",
  "Start Y": "editor.ui.props.label.startY",
  "Suffix": "editor.ui.props.label.suffix",
  "Suppress Zeros": "editor.ui.props.label.suppressZeros",
  "Text": "editor.ui.props.label.text",
  "Text Height": "editor.ui.props.label.textHeight",
  "Text Offset": "editor.ui.props.label.textOffset",
  "Text Override": "editor.ui.props.label.textOverride",
  "Text Placement": "editor.ui.props.label.textPlacement",
  "Text Rotation": "editor.ui.props.label.textRotation",
  "Text frame": "editor.ui.props.label.textFrame",
  "Transparency": "editor.ui.props.label.transparency",
  "Type": "editor.ui.props.label.type",
  "Underline": "editor.ui.props.label.underline",
  "Unit Format": "editor.ui.props.label.unitFormat",
  "Value": "editor.ui.props.label.value",
  "Vertex Count": "editor.ui.props.label.vertexCount",
  "Width": "editor.ui.props.label.width",
  "Width Factor": "editor.ui.props.label.widthFactor",
  "X Datum": "editor.ui.props.label.xDatum",
};

export const PROPERTY_CATEGORY_KEYS: Readonly<Record<string, string>> = {
  "Appearance": "editor.ui.props.category.appearance",
  "Arrows": "editor.ui.props.category.arrows",
  "Attributes": "editor.ui.props.category.attributes",
  "Background": "editor.ui.props.category.background",
  "Block": "editor.ui.props.category.block",
  "Cell Contents": "editor.ui.props.category.cellContents",
  "Display": "editor.ui.props.category.display",
  "General": "editor.ui.props.category.general",
  "Geometry": "editor.ui.props.category.geometry",
  "Leader": "editor.ui.props.category.leader",
  "MLeader": "editor.ui.props.category.mleader",
  "Pattern": "editor.ui.props.category.pattern",
  "Structure": "editor.ui.props.category.structure",
  "Style": "editor.ui.props.category.style",
  "Text": "editor.ui.props.category.text",
  "Units": "editor.ui.props.category.units",
};
